name: canteen_app
description: A Flutter project with forced update system, single device authentication, and stock reservation system.
publish_to: 'none'

# IMPORTANT: Change these values for each update!
version: 1.0.1+2  # Increment build number (+2) for forced updates

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - STABLE VERSIONS for compatibility
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  cloud_functions: ^4.7.6
  
  # UI & Design
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Authentication - STABLE VERSION
  google_sign_in: ^6.1.5
  
  # Notifications - FIXED VERSION
  flutter_local_notifications: ^17.2.3
  
  # Payment
  razorpay_flutter: ^1.3.6
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Image
  image_picker: ^1.0.4
  
  # Device Info - REQUIRED FOR DEVICE MANAGEMENT
  device_info_plus: ^9.1.1
  
  # Network & Connectivity - ADDED FOR ENHANCED ERROR HANDLING
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  
  # UI Enhancements - ADDED FOR BETTER UX DURING ERRORS/LOADING
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  
  # Error Reporting & Logging - ADDED FOR BETTER MONITORING
  logging: ^1.2.0
  
  # Permissions - ADDED FOR BETTER PERMISSION HANDLING
  permission_handler: ^11.2.0
  
  # NEW DEPENDENCIES FOR FORCED UPDATE SYSTEM
  package_info_plus: ^4.2.0      # Get app version info
  url_launcher: ^6.2.1           # Launch app store URLs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # REMOVED: Commented out assets and fonts until you create the directories
  # Uncomment these after creating the asset folders and files
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700